---
title: "Homework 4"
format:
  html:
    embed-resources: true
editor: visual
---

Link to Github repository: https://github.com/grobertson881/stats506-homework4

**Problem 1** 

```{r}
#install.packages("nzelect")
library(nzelect)
library(tidyverse)
nzge <- nzelect::nzge
```

*Part A*
```{r}
vote_count <- nzge %>% 
  select(votes, election_year, voting_type) %>%
  group_by(election_year, voting_type) %>% 
  summarize(total_vote_count = sum(votes)) %>% 
  arrange(total_vote_count)

vote_count
```

*Part B*
```{r}
votes_2014 <- nzge %>% 
  filter(election_year == 2014, voting_type == "Candidate") %>% 
  group_by(party) %>% 
  summarize(party_total_votes = sum(votes)) %>% 
  ungroup() %>% 
  mutate(vote_proportion = party_total_votes / sum(party_total_votes) * 100) %>% 
  select(-party_total_votes) %>% 
  arrange(desc(vote_proportion))
  
votes_2014
```

*Part C*
```{r}
winning_party <- nzge %>% 
  group_by(election_year, voting_type) %>% 
  filter(votes == max(votes)) %>% 
  select(election_year, voting_type, party)
  
winning_party
```

**Problem 2**
```{r}
tennis <- read_csv("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/refs/heads/master/atp_matches_2019.csv")
```

*Part A*
```{r}
tourney_2019 <- tennis %>% 
  mutate(tourney_date = as.character(tourney_date)) %>% 
  filter(str_sub(tourney_date, 1, 4) == "2019") %>% 
  summarise(num_tourneys_2019 = n_distinct(tourney_id))

tourney_2019
```
There were 125 tournaments in 2019. 

*Part B*
```{r}

```

Answer: 

*Part C*
```{r}

```

Answer:

*Part D*
```{r}

```

Answer: 

**Problem 3**
```{r}
covid <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/refs/heads/master/rolling-averages/us-states.csv")
```

*Part A*
```{r}
michigan_cases <- covid %>% 
  filter(state == "Michigan")

# add find peaks and add to graph

ggplot(michigan_cases, aes(x = date, y = cases_avg)) + 
  geom_line(linewidth = 1)

```

Answer:

*Part B*
```{r}

```

Answer: 

*Part C*
```{r}

```

Answer: 











